name: ci-pipeline

on: [push]

jobs:
  model_train_evaluate:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: 'Train and Evaluate Model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Intall all dependencies
          pip install -r requirements.txt
          
          dvc repro
          
          git fetch --prune
          dvc metrics diff --show-md main > report.md
          cml comment create report.md
          
