name: ci-pipeline

on: [push]

jobs:
  CI-Pipeline:
    runs-on: [ubuntu-latest]
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Install CML
        uses: iterative/setup-cml@v1
        
      - name: Install DVC
        uses: iterative/setup-dvc@v1
        
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          
        
      - name: Install all dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Load Data
        run: |
          dvc repro dvc.yaml:load_data
          
      - name: Split Data
        run: |
          dvc repro dvc.yaml:split_data
          
      - name: Train and Evaluate
        run: |
          dvc repro dvc.yaml:train_and_evaluate
          
      - name: Generate Report
        run: |          
          git fetch --prune
          dvc metrics diff --show-md main > report.md
          cml comment create report.md
          
